openapi: 3.0.3
info:
  title: Vending Machine
  description: |-
    API Documentations

    URL Dev : [http://192.168.1.83/etopup/public/api](http://192.168.1.83)
  version: 1.0.0
  contact: {}
servers:
  - url: '{{base_url}}'
  - url: 'https://api.getpostman.com'
paths:
  /logindevice:
    get:
      summary: Get all data logindevice
      description: Get all data logindevice
      operationId: getAllDataLogindevice
      responses:
        '200':
          description: '200'
          headers:
            Cache-Control:
              schema:
                type: string
                example: 'no-cache, private'
            Connection:
              schema:
                type: string
                example: close
            Date:
              schema:
                type: string
                example: 'Tue, 21 Jan 2025 10:41:38 GMT'
            Server:
              schema:
                type: string
                example: Apache/2.2.15 (CentOS)
            Transfer-Encoding:
              schema:
                type: string
                example: chunked
            X-Powered-By:
              schema:
                type: string
                example: PHP/7.2.33
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        active:
                          type: number
                          example: 1
                        id:
                          type: number
                          example: 1
                        id_kartu:
                          type: string
                          example: '100001'
                        last_access:
                          type: string
                          example: '2005-09-09 19:47:28'
                        shift:
                          type: number
                          example: 1
                        sn_device:
                          type: string
                          example: J700000155
                        sn_kartu:
                          type: string
                          example: F51FDDA0
                        tid:
                          type: string
                          example: '51510201'
                        waktu_buka:
                          type: string
                          example: '13:30:00'
                        waktu_tutup:
                          type: string
                          example: '22:00:00'
                    example:
                      - active: 1
                        id: 1
                        id_kartu: '100001'
                        last_access: '2005-09-09 19:47:28'
                        shift: 1
                        sn_device: J700000155
                        sn_kartu: F51FDDA0
                        tid: '51510201'
                        waktu_buka: '13:30:00'
                        waktu_tutup: '22:00:00'
                      - active: 1
                        id: 2
                        id_kartu: '100001'
                        last_access: '2019-12-17 08:33:51'
                        shift: 2
                        sn_device: J700000155
                        sn_kartu: F51FDDA0
                        tid: '51510201'
                        waktu_buka: '13:30:00'
                        waktu_tutup: '22:00:00'
                  responseLocal:
                    type: object
                    properties:
                      responseCode:
                        type: string
                        example: '00'
                      responseDesc:
                        type: string
                        example: Success
              examples:
                '200':
                  value:
                    data:
                      - active: 1
                        id: 1
                        id_kartu: '100001'
                        last_access: '2005-09-09 19:47:28'
                        shift: 1
                        sn_device: J700000155
                        sn_kartu: F51FDDA0
                        tid: '51510201'
                        waktu_buka: '13:30:00'
                        waktu_tutup: '22:00:00'
                      - active: 1
                        id: 2
                        id_kartu: '100001'
                        last_access: '2019-12-17 08:33:51'
                        shift: 2
                        sn_device: J700000155
                        sn_kartu: F51FDDA0
                        tid: '51510201'
                        waktu_buka: '13:30:00'
                        waktu_tutup: '22:00:00'
                    responseLocal:
                      responseCode: '00'
                      responseDesc: Success
      security:
        - {}
    post:
      summary: Login
      description: Login
      operationId: login
      parameters:
        - name: tid
          in: query
          schema:
            type: string
            example: 099999999
        - name: sn_device
          in: query
          schema:
            type: string
            example: '00005274'
        - name: sn_kartu
          in: query
          schema:
            type: string
            example: F178271F
        - name: id_kartu
          in: query
          schema:
            type: string
            example: '100024'
        - name: shift
          in: query
          schema:
            type: string
            example: '1'
        - name: tipe
          in: query
          schema:
            type: string
            example: '20'
      responses:
        '200':
          description: ''
  '/collections/{collection_id}/transformations':
    get:
      summary: Open API Documentation
      description: Open API Documentation
      operationId: openApiDocumentation
      responses:
        '200':
          description: ''
      security:
        - apiKey: []
    parameters:
      - name: collection_id
        in: path
        required: true
        schema:
          type: string
          example: 7085933-cd52be11-a626-44ea-a3b4-4d54da92f92f
        description: Get from collection details
components:
  securitySchemes:
    apiKey:
      type: apiKey
      name: X-API-Key
      in: header
tags: []