openapi: 3.0.3
info:
  title: Vending Machine
  description: |-
    API Documentations

    URL Dev : [http://192.168.1.83/etopup/public](http://192.168.1.83)
  version: 1.0.0
  contact: {}
servers:
  - url: '{{base_url}}'
  - url: 'https://api.getpostman.com'
paths:
  /api/logindevice:
    get:
      tags:
        - Login Device
      summary: Get all data logindevice
      description: >-
        Endpoint ini digunakan untuk get all data, select all dari tabel
        login_device.
      operationId: getAllDataLogindevice
      responses:
        '200':
          description: Success / Data not found
          headers:
            Cache-Control:
              schema:
                type: string
                example: 'no-cache, private'
            Connection:
              schema:
                type: string
                example: close
            Date:
              schema:
                type: string
                example: 'Tue, 21 Jan 2025 10:41:38 GMT'
            Server:
              schema:
                type: string
                example: Apache/2.2.15 (CentOS)
            Transfer-Encoding:
              schema:
                type: string
                example: chunked
            X-Powered-By:
              schema:
                type: string
                example: PHP/7.2.33
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        active:
                          type: number
                          example: 1
                        id:
                          type: number
                          example: 1
                        id_kartu:
                          type: string
                          example: '100001'
                        last_access:
                          type: string
                          example: '2005-09-09 19:47:28'
                        shift:
                          type: number
                          example: 1
                        sn_device:
                          type: string
                          example: J700000155
                        sn_kartu:
                          type: string
                          example: F51FDDA0
                        tid:
                          type: string
                          example: '51510201'
                        waktu_buka:
                          type: string
                          example: '13:30:00'
                        waktu_tutup:
                          type: string
                          example: '22:00:00'
                    example:
                      - active: 1
                        id: 1
                        id_kartu: '100001'
                        last_access: '2005-09-09 19:47:28'
                        shift: 1
                        sn_device: J700000155
                        sn_kartu: F51FDDA0
                        tid: '51510201'
                        waktu_buka: '13:30:00'
                        waktu_tutup: '22:00:00'
                      - active: 1
                        id: 2
                        id_kartu: '100001'
                        last_access: '2019-12-17 08:33:51'
                        shift: 2
                        sn_device: J700000155
                        sn_kartu: F51FDDA0
                        tid: '51510201'
                        waktu_buka: '13:30:00'
                        waktu_tutup: '22:00:00'
                  responseLocal:
                    type: object
                    properties:
                      responseCode:
                        type: string
                        example: '00'
                      responseDesc:
                        type: string
                        example: Success
              examples:
                Data not found:
                  value:
                    responseLocal:
                      responseCode: '28'
                      responseDesc: Empty Data
                Success:
                  value:
                    data:
                      - active: 1
                        id: 1
                        id_kartu: '100001'
                        last_access: '2005-09-09 19:47:28'
                        shift: 1
                        sn_device: J700000155
                        sn_kartu: F51FDDA0
                        tid: '51510201'
                        waktu_buka: '13:30:00'
                        waktu_tutup: '22:00:00'
                      - active: 1
                        id: 2
                        id_kartu: '100001'
                        last_access: '2019-12-17 08:33:51'
                        shift: 2
                        sn_device: J700000155
                        sn_kartu: F51FDDA0
                        tid: '51510201'
                        waktu_buka: '13:30:00'
                        waktu_tutup: '22:00:00'
                    responseLocal:
                      responseCode: '00'
                      responseDesc: Success
      security:
        - {}
    post:
      tags:
        - Login Device
      summary: Login
      description: >-
        Endpoint ini digunakan untuk login, parameter yang dikirimkan akan di
        cek persamaan data nya pada  

        tabel login_device. Apabila data tersebut valid, maka akan memberikan
        respon data hasil dari select all ke tabel login_device.
      operationId: login
      parameters:
        - name: tid
          in: query
          schema:
            type: string
            example: 099999999
        - name: sn_device
          in: query
          schema:
            type: string
            example: '00005274'
        - name: sn_kartu
          in: query
          schema:
            type: string
            example: F178271F
        - name: id_kartu
          in: query
          schema:
            type: string
            example: '100024'
        - name: shift
          in: query
          schema:
            type: string
            example: '1'
        - name: tipe
          in: query
          schema:
            type: string
            example: '20'
      responses:
        '200':
          description: Success / Data not found
          headers:
            Cache-Control:
              schema:
                type: string
                example: 'no-cache, private'
            Connection:
              schema:
                type: string
                example: close
            Content-Length:
              schema:
                type: string
                example: '67'
            Date:
              schema:
                type: string
                example: 'Wed, 22 Jan 2025 01:50:33 GMT'
            Server:
              schema:
                type: string
                example: Apache/2.2.15 (CentOS)
            X-Powered-By:
              schema:
                type: string
                example: PHP/7.2.33
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      active:
                        type: number
                        example: 1
                      app_version:
                        type: string
                        example: '100'
                      id:
                        type: number
                        example: 1406
                      id_kartu:
                        type: string
                        example: '100024'
                      last_access:
                        type: string
                        example: '2025-01-22 08:49:16'
                      shift:
                        type: number
                        example: 1
                      sn_device:
                        type: string
                        example: '00005274'
                      sn_kartu:
                        type: string
                        example: F178271F
                      tid:
                        type: string
                        example: 099999999
                      tipe:
                        type: number
                        example: 20
                      waktu_buka:
                        nullable: true
                        example: ~
                      waktu_tutup:
                        nullable: true
                        example: ~
                  responseLocal:
                    type: object
                    properties:
                      responseCode:
                        type: string
                        example: '00'
                      responseDesc:
                        type: string
                        example: Updated
              examples:
                Data not found:
                  value:
                    responseLocal:
                      responseCode: '28'
                      responseDesc: Empty Data
                Success:
                  value:
                    data:
                      active: 1
                      app_version: '100'
                      id: 1406
                      id_kartu: '100024'
                      last_access: '2025-01-22 08:49:16'
                      shift: 1
                      sn_device: '00005274'
                      sn_kartu: F178271F
                      tid: 099999999
                      tipe: 20
                      waktu_buka: ~
                      waktu_tutup: ~
                    responseLocal:
                      responseCode: '00'
                      responseDesc: Updated
  /api/merchant:
    get:
      tags:
        - Merchant
      summary: Get all data merchant
      description: 'Digunakan untuk get all data, select all dari tabel merchant.'
      operationId: getAllDataMerchant
      responses:
        '200':
          description: Success / Data not found
          headers:
            Cache-Control:
              schema:
                type: string
                example: 'no-cache, private'
            Connection:
              schema:
                type: string
                example: close
            Date:
              schema:
                type: string
                example: 'Tue, 21 Jan 2025 10:41:38 GMT'
            Server:
              schema:
                type: string
                example: Apache/2.2.15 (CentOS)
            Transfer-Encoding:
              schema:
                type: string
                example: chunked
            X-Powered-By:
              schema:
                type: string
                example: PHP/7.2.33
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        client_id:
                          type: string
                          example: gHY7C2rr05uSAyh3PRxuGr1xTfb8itgH
                        desk:
                          type: string
                          example: PT. HK ATP
                        idcabang:
                          type: string
                          example: '5151'
                        idmerchant:
                          type: string
                          example: '000001'
                        lokasi:
                          type: string
                          example: TANJUNG PRIOK
                    example:
                      - client_id: gHY7C2rr05uSAyh3PRxuGr1xTfb8itgH
                        desk: PT. HK ATP
                        idcabang: '5151'
                        idmerchant: '000001'
                        lokasi: TANJUNG PRIOK
                      - client_id: gHY7C2rr05uSAyh3PRxuGr1xTfb8itgH
                        desk: PT. JLJ
                        idcabang: '0315'
                        idmerchant: '000002'
                        lokasi: JATI ASIH
                  responseLocal:
                    type: object
                    properties:
                      responseCode:
                        type: string
                        example: '00'
                      responseDesc:
                        type: string
                        example: Success
              examples:
                Data not found:
                  value:
                    responseLocal:
                      responseCode: '28'
                      responseDesc: Empty Data
                Success:
                  value:
                    data:
                      - client_id: gHY7C2rr05uSAyh3PRxuGr1xTfb8itgH
                        desk: PT. HK ATP
                        idcabang: '5151'
                        idmerchant: '000001'
                        lokasi: TANJUNG PRIOK
                      - client_id: gHY7C2rr05uSAyh3PRxuGr1xTfb8itgH
                        desk: PT. JLJ
                        idcabang: '0315'
                        idmerchant: '000002'
                        lokasi: JATI ASIH
                    responseLocal:
                      responseCode: '00'
                      responseDesc: Success
      security:
        - {}
    post:
      tags:
        - Merchant
      summary: Merchant
      description: >-
        Digunakan untuk insert data ke tabel merchant dari parameter yang
        dikirim. apabila insert data merchant berhasil, maka akan memberikan
        respon data tersebut select dari tabel merchant berdasarkan idmerchant
        yang baru di insert.
      operationId: merchant
      parameters:
        - name: idmerchant
          in: query
          schema:
            type: string
            example: '999903'
        - name: desk
          in: query
          schema:
            type: string
            example: Development 3
        - name: lokasi
          in: query
          schema:
            type: string
            example: Development 3
        - name: client_id
          in: query
          schema:
            type: string
            example: gHY7C2rr05uSAyh3PRxuGr1xTfb8itgH
      responses:
        '200':
          description: Success / Data duplicate
          headers:
            Cache-Control:
              schema:
                type: string
                example: 'no-cache, private'
            Connection:
              schema:
                type: string
                example: close
            Content-Length:
              schema:
                type: string
                example: '94'
            Date:
              schema:
                type: string
                example: 'Wed, 22 Jan 2025 02:39:55 GMT'
            Server:
              schema:
                type: string
                example: Apache/2.2.15 (CentOS)
            X-Powered-By:
              schema:
                type: string
                example: PHP/7.2.33
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      client_id:
                        type: string
                        example: gHY7C2rr05uSAyh3PRxuGr1xTfb8itgH
                      desk:
                        type: string
                        example: Development 3
                      idcabang:
                        nullable: true
                        example: ~
                      idmerchant:
                        type: string
                        example: '999903'
                      lokasi:
                        type: string
                        example: Development 3
                  responseLocal:
                    type: object
                    properties:
                      responseCode:
                        type: string
                        example: '00'
                      responseDesc:
                        type: string
                        example: Created
              examples:
                Data duplicate:
                  value:
                    responseLocal:
                      responseCode: '43'
                      responseDesc: Duplicate entry for IdMerchant 999999
                Success:
                  value:
                    data:
                      client_id: gHY7C2rr05uSAyh3PRxuGr1xTfb8itgH
                      desk: Development 3
                      idcabang: ~
                      idmerchant: '999903'
                      lokasi: Development 3
                    responseLocal:
                      responseCode: '00'
                      responseDesc: Created