openapi: 3.0.3
info:
  title: Vending Machine
  description: |-
    API Documentations

    URL Dev : [http://192.168.1.83/etopup/public/api](http://192.168.1.83)
  version: 1.0.0
  contact: {}
servers:
  - url: '{{base_url}}'
  - url: 'https://api.getpostman.com'
paths:
  /logindevice:
    get:
      summary: Get all data logindevice
      description: Get all data logindevice
      operationId: getAllDataLogindevice
      responses:
        '200':
          description: ''
      security:
        - {}
    post:
      summary: Login
      description: Login
      operationId: login
      parameters:
        - name: tid
          in: query
          schema:
            type: string
            example: 099999999
        - name: sn_device
          in: query
          schema:
            type: string
            example: '00005274'
        - name: sn_kartu
          in: query
          schema:
            type: string
            example: F178271F
        - name: id_kartu
          in: query
          schema:
            type: string
            example: '100024'
        - name: shift
          in: query
          schema:
            type: string
            example: '1'
        - name: tipe
          in: query
          schema:
            type: string
            example: '20'
      responses:
        '200':
          description: ''
  '/collections/{collection_id}/transformations':
    get:
      summary: Open API Documentation
      description: Open API Documentation
      operationId: openApiDocumentation
      responses:
        '200':
          description: ''
      security:
        - apiKey: []
    parameters:
      - name: collection_id
        in: path
        required: true
        schema:
          type: string
          example: 7085933-cd52be11-a626-44ea-a3b4-4d54da92f92f
        description: Get from collection details
components:
  securitySchemes:
    apiKey:
      type: apiKey
      name: X-API-Key
      in: header
tags: []